# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
  - cron: 0 14 * * *
    displayName: send csv file everyday on 14:00
    branches: 
      include: 
        - master

variables:
  group: NotJustTestVar
  
  
pool:
  name: 'test task pool'

steps:  
- script: ./scripts/get_variable_groups_in_releases.sh
  displayName: 'get release data into json file'

- script: ./scripts/get_variable_groups.sh
  displayName: 'get all variable groups'

- script: python ./scripts/json_to_csv.py
  displayName: 'convert json data to csv'
  env:
    JSON_VARIABLES_GROUPS: $(JSON_VARIABLES_GROUPS)
    JSON_OUTPUT_FILE: $(JSON_OUTPUT_FILE)
    CSV_OUTPUT_FILE: $(CSV_OUTPUT_FILE)

- script: python ./scripts/send_csv_to_slack.py
  displayName: 'send file to slack'
  env:
    SLACK_BOT_TOKEN: $(SLACK_BOT_TOKEN)
    SLACK_CHANNEL_ID: $(SLACK_CHANNEL_ID)
    CSV_OUTPUT_FILE: $(CSV_OUTPUT_FILE)